### ISSUE TITLE
Demo URL not working

### ISSUE THREAD

**Issue by lyndseybrowning** [rbrtsmith/nebula-css#8]
Hey Rob, the "view the demo" URL provided in the README directs to a 404 error.

**Comment by rbrtsmith** [comment]
Cheers.  I've fixed that, those docs are now stale.

You can find the new documentation here https://nebulaui.github.io/nebula/

which encompasses all of the Nebula UI repos.

**Comment by bricejar** [comment]
Links are still dead in the documentation.

**Comment by rbrtsmith** [comment]
Hi @bricejar Which links are you talking about?  I've just checked those at the top of the README and I don't see any 404s

**Comment by bricejar** [comment]
![image](https://user-images.githubusercontent.com/45051524/54561087-2ff6b780-499a-11e9-9892-743f8875f4d4.png)

Most "demo" links.

**Comment by rbrtsmith** [comment]
Thanks for alerting me to this @bricejar.  I've removed / fixed the stale urls appropriately.
